{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"hey, does this work?\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Day 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "d1_test = \"\"\"1000\n",
    "2000\n",
    "3000\n",
    "\n",
    "4000\n",
    "\n",
    "5000\n",
    "6000\n",
    "\n",
    "7000\n",
    "8000\n",
    "9000\n",
    "\n",
    "10000\"\"\"\n",
    "d1_data = \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def d1p1(x):\n",
    "    elf_sums = []\n",
    "    for elf in x.split(\"\\n\\n\"):\n",
    "        elf_sums.append(sum([int(x) for x in elf.splitlines()]))\n",
    "    print(max(elf_sums))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Day 7"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 113, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 827, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/configurable.py\", line 200, in _load_config\n",
      "\u001b[1;31m    warn(msg)\n",
      "\u001b[1;31m  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py\", line 124, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/burningshed/AdventOfCode''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 984, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 113, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 113, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 117, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 972, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 11:11:38.383 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/burningshed/AdventOfCode''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/burningshed/AdventOfCode\" --config=/var/folders/tm/7f6ypd3s61qbhlgdthrnts700000gn/T/427c32f2-1a39-4309-8770-a6cd30d1af38/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "d6_test = \"\"\"$ cd /\n",
    "$ ls\n",
    "dir a\n",
    "14848514 b.txt\n",
    "8504156 c.dat\n",
    "dir d\n",
    "$ cd a\n",
    "$ ls\n",
    "dir e\n",
    "29116 f\n",
    "2557 g\n",
    "62596 h.lst\n",
    "$ cd e\n",
    "$ ls\n",
    "584 i\n",
    "$ cd ..\n",
    "$ cd ..\n",
    "$ cd d\n",
    "$ ls\n",
    "4060174 j\n",
    "8033020 d.log\n",
    "5626152 d.ext\n",
    "7214296 k\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 113, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 827, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/configurable.py\", line 200, in _load_config\n",
      "\u001b[1;31m    warn(msg)\n",
      "\u001b[1;31m  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py\", line 124, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/burningshed/AdventOfCode''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 984, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 113, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 113, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 117, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/robertwoehrle/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py\", line 972, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 11:11:38.383 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/burningshed/AdventOfCode''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/burningshed/AdventOfCode\" --config=/var/folders/tm/7f6ypd3s61qbhlgdthrnts700000gn/T/427c32f2-1a39-4309-8770-a6cd30d1af38/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "from collections import defaultdict\n",
    "from pathlib import PurePosixPath\n",
    "def dir_dict_fact():\n",
    "    return [0, set()]\n",
    "class compute:\n",
    "    # dictionary of directories (name - key, value - set of subdirs, \n",
    "    # position o is size)\n",
    "    def __init__(self):\n",
    "        self.dir_dict = defaultdict(dir_dict_fact)\n",
    "        self.cur_dir = PurePosixPath()\n",
    "        self.com_dict = {\n",
    "            \"cd\" : self.cd,\n",
    "            \"ls\" : self.ls\n",
    "        }\n",
    "    def ls(self, args):\n",
    "        pass\n",
    "    def cd(self, args):\n",
    "        if args[1] == \"..\":\n",
    "            self.cur_dir = self.cur_dir.parent \n",
    "        else:\n",
    "            self.cur_dir = self.cur_dir / args[1]\n",
    "\n",
    "    def command(self, args):\n",
    "        return self.com_dict[args[0]](args)\n",
    "    def add_file(self, filesize):\n",
    "        self.dir_dict[self.cur_dir][0] += filesize\n",
    "    def add_dir(self, dirname):\n",
    "        self.dir_dict[self.cur_dir][1].\n",
    "        \n",
    "\n",
    "def d7p1(x):\n",
    "    cur = compute()\n",
    "    for line in x:\n",
    "        if line[0] == \"$\":\n",
    "            cur.command(line.split()[1:])\n",
    "        elif line[0] == \"d\":\n",
    "            # is there anything I want to do when finding a dir\n",
    "            pass\n",
    "        else:\n",
    "            cur.add_file(int(line.split()[0]))\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.13 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.9.13"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "8ca901e7953aa48edaef8b6e21a61592dcc39c93e1b6d2244f8725e806931399"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
